services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: signals
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ecg-api:
    build: .
    container_name: ecg-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://app:app@db:5432/signals

volumes:
  pgdata: